spring:
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/practice_spring
    username: postgres
    password: postgrestest
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true